version: "3"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - ./index.js:/app/index.js:ro
    ports:
      - "4000:4000"
    env_file:
      - ./.env